image: python:3.8

cache:
  paths:
    - .venv

stages:
  - test
  - deploy

before_script:
  - pip install poetry
  - poetry config virtualenvs.in-project true
  - poetry install
  - source .venv/bin/activate

unittest:
  stage: test
  script:
    - python -m unittest

deploy_master:
  stage: deploy
  script:
    - poetry config repositories.gitlab ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi
    - poetry build
    - poetry publish --repository gitlab -u gitlab-ci-token -p ${CI_JOB_TOKEN}
  only:
    - master
  except:
    - tags
