image: python:3.10

variables:
  GIT_SUBMODULE_STRATEGY: normal

cache:
  key:
    files:
      - poetry.lock
  paths:
    - .venv

stages:
  - style
  # test-unit runs simple unit tests which are quickly executed.
  - test-unit
  # test-integration runs more complex integration tests, e.g. rule evaluation which is quite resources intensive.
  - test-integration
  - deploy

before_script: &default_before_script
  - pip install poetry
  - poetry config virtualenvs.in-project true
  - poetry config system-git-client true
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.lrz.de".insteadOf "ssh://git@gitlab.lrz.de"


pre_commit:
  stage: style
  before_script:
    - *default_before_script
    - poetry install --extras dev
  script:
    - poetry run pre-commit run --all-files --show-diff-on-failure

test_python_unit:
  stage: test-unit
  before_script:
    - *default_before_script
    - poetry install -vvv --extras test
  script:
    - poetry run coverage run --source=./crmonitor -m pytest tests/unit
    - poetry run coverage report -m || true
    - poetry run coverage xml
  coverage: /(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

test_python_integration:
  stage: test-integration
  before_script:
    - *default_before_script
    - poetry install -vvv --extras test
  script:
    - poetry run coverage run --source=./crmonitor -m pytest tests/integration
    - poetry run coverage report -m || true
    - poetry run coverage xml
  coverage: /(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

deploy_master:
  stage: deploy
  script:
    - poetry config repositories.gitlab ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi
    - poetry build
    - poetry publish --repository gitlab -u gitlab-ci-token -p ${CI_JOB_TOKEN}
  only:
    - master
  except:
    - tags

sphinx:
  stage: test-unit
  needs: []
  before_script:
    - *default_before_script
    - apt-get update && apt-get install -y build-essential graphviz graphviz-dev
    - poetry install --extras doc
  script:
    - cd docs/source && poetry run sphinx-build -b html -W . ../build

pages:
  stage: deploy
  needs:
  - sphinx
  before_script:
    - *default_before_script
    - apt-get update && apt-get install -y build-essential graphviz graphviz-dev
    - poetry install --extras doc
  script:
    - cd docs/source && sphinx-build -b html . ../../public
  artifacts:
    paths:
    - public
  only:
    - development
