image: continuumio/anaconda3

stages:
- test

before_script:
- bash ./ci/install_third_party_software.sh
- conda create -n commonroad python=3.6

python36:
  stage: test
  script:
    - source activate commonroad
    - pip install tox coverage
    #- git clone https://gitlab.lrz.de/tum-cps/commonroad-drivability-checker.git
    #- echo "Building commonroad drivability checker"
    #- cd commonroad-drivability-checker

    #- bash build.sh -e "/opt/conda/envs/commonroad/" -v 3.6 --cgal --serializer --no-root -j 1
    # Aloow permissions to all repositories
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.lrz.de/".insteadOf "git@gitlab.lrz.de:"
    # commonroad-io
    - git clone --branch develop git@gitlab.lrz.de:cps/commonroad-io.git $HOME/commonroad-io
    - pip install -e $HOME/commonroad-io
    # curvilinear-coordinate-system
    - git clone --branch development git@gitlab.lrz.de:cps/commonroad-curvilinear-coordinate-system.git $HOME/commonroad-curvilinear-coordinate-system
    - cd $HOME/commonroad-curvilinear-coordinate-system/
    - mkdir -p build
    - cd build
    - cmake -DADD_PYTHON_BINDINGS=TRUE -DPATH_TO_PYTHON_ENVIRONMENT="/opt/conda/envs/commonroad/" -DPYTHON_VERSION="3.6" -DCMAKE_BUILD_TYPE=Release ..
    - make
    - cd ..
    - python setup.py install
    - cd $CI_PROJECT_DIR
    # test
    - pip install -r ./requirements.txt
    - pip install -e .[tests]
    - coverage run -m pytest tests
    - coverage report -m || true
