repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
    # The mkdocs.yml contains a string that is not supported by check-yaml, but is according to the mkdocs spec.
    exclude: mkdocs.yml
  - id: check-added-large-files
    exclude: crmonitor/mpr/models
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.13.2
  hooks:
  # TODO: Enable linting with ruff. It is disable for now, because too much of the code base has linting errors.
  - id: ruff
    args: [--fix]
  - id: ruff-format
- repo: https://github.com/python-poetry/poetry
  rev: 2.2.1
  hooks:
  - id: poetry-check
