repos:
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
    name: isort (python)
    args: [--profile, black, --filter-files, --line-width=88]
- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
  - id: black
#  - repo: https://gitlab.com/pycqa/flake8
#    rev: 3.7.9
#    hooks:
#      - id: flake8
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.5.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']

