[tool.poetry]
name = "commonroad-stl-monitor"
version = "0.1.0"
description = ""
authors = ["Luis Gressenbuch <luis.gressenbuch@tum.de>"]
readme = "README.md"
packages = [{include = "crmonitor"}]

[tool.poetry.dependencies]
python = "^3.8"
commonroad-io = "2022.1"
commonroad-vehicle-models = ">=2"
ruamel-yaml = ">=0.16.12"
commonroad-drivability-checker = ">=2021.4"
antlr4-python3-runtime = ">=4.5,<4.6"
numba = "^0.56.0"
rtamt = {git = "https://github.com/cirrostratus1/rtamt.git", rev = "6ef48e956837f5b60f514011d3d6eabf6307e042"}
pendulum = "^2.1.2"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
coverage = "^6.5.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
