[tool.poetry]
name = "commonroad-stl-monitor"
version = "2024.1"
description = ""
authors = ["Luis Gressenbuch <luis.gressenbuch@tum.de>, Yuanfei Lin <yuanfei.lin@tum.de>"]
readme = "README.md"
packages = [
    {include = "crmonitor"},
    # Vendor rtamt to let omegaconf decide on the antlr version.
    { from = "external/rtamt", include = "rtamt" }
]

[tool.poetry.dependencies]
python = ">=3.9, <3.12"
commonroad-io = ">=2024.3"
ruamel-yaml = ">=0.16.12"
commonroad-route-planner = "^2025.1.0"
numba = ">=0.58.1"
commonroad-mpr = { git = "ssh://git@gitlab.lrz.de/cps/commonroad-model-predictive-robustness.git", rev = "02273bdb8fede24b0f1e6ecf93cd2479e1850e2d" }
pyqt6 = "^6.8.1"
commonroad-clcs = "^2025.1.1"
commonroad-drivability-checker = "^2025.1"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
coverage = "^6.5.0"
# To run the tests, we necessarily need this commonroad-io version
commonroad-io = ">=2024.1"

[tool.poetry.group.doc]
optional = true

[tool.poetry.group.doc.dependencies]
sphinx = "^5.3.0"
myst-parser = "^0.18.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
