py_library(
	name="crmonitor",
	srcs = glob(["**/*.py"]),
	visibility = ["//visibility:public"],
	deps=["//crmonitor/common:common"],
)

filegroup(
	name="data_files",
	srcs = glob(["**/*.yaml"]),
	visibility = ["//visibility:public"],
)