image: continuumio/anaconda3 # crmonitor #

stages:
- test

before_script:
- echo ${CI_JOB_TOKEN}
- eval $CI_PRE_CLONE_SCRIPT
- conda create -n commonroad python=3.6
- source activate commonroad
- bash ./ci/install_third_party_software.sh


python36:
  stage: test
  # tags: 
  #   - test
  script:
    - source activate commonroad
    - bash ./ci/install_cps_software.sh
    - pip install tox coverage
    - pip install -r ./requirements.txt
    - pip install -e .[tests]
    - coverage run -m pytest tests
    - coverage report -m || true
