variables:
  pull_policy: never

build:
  image: 
    name: crmonitor #continuumio/anaconda3
    pull_policy: if-not-present

stages:
- test

before_script:
#- conda create -n commonroad python=3.6
#- source activate commonroad
- bash ./ci/install_third_party_software.sh


python36:
  stage: test
  script:
    - source activate commonroad
    - bash ./ci/install_cps_software.sh
    - pip install tox coverage
    - pip install -r ./requirements.txt
    - pip install -e .[tests]
    - coverage run -m pytest tests
    - coverage report -m || true
