
# simulation parameters
###
# .. code-block:: yaml
#
#    - dt: time step size
#    - commonroad_benchmark_id: CommonRoad solution file name
#    - commonroad_scenario_folder: folder in which CommonRoad scenarios are located
#    - verbose_mode: activate/deactivate status output of algorithms and simulation
#    - time_measuring: activate/deactivate computation time measuring
#    - c_profile: activate/deactivate storing of computation time by using cProfile package
#    - commonroad_video_creation: activate/deactivate video creation of CommonRoad scenario
#    - profile_video_creation: activate/deactivate video creation of profiles
#    - plotting: activate/deactivate plotting of state profiles
#    - other_vehicle_plots: list with CommonRoad obstacle IDs which should be considered for plotting
#    - store_profiles: activate/deactivate storage of profiles
#    - video_output_folder: folder in which the created videos are stored
#    - country: country of scenario
simulation_param:
    dt: 0.1
    commonroad_benchmark_id: USA_US101-33_1_T-1
    commonroad_scenario_folder: ./scenarios/test/
    verbose_mode: true
    time_measuring: true
    c_profile: false
    commonroad_video_creation: false
    profile_video_creation: false
    plotting: false
    other_vehicle_plots: [140]
    store_profiles: false
    video_output_folder: ./videos
    country: "DEU"

# road network and curvilinear coordinate system parameters
###
# .. code-block:: yaml
#
#    - num_chankins_corner_cutting: number of how often chankins algorithm should be applied
#    - polyline_resampling_step: step size for polyline resampling
#    - merging_length: maximum accumulated length of lanalets belonging to a lane
road_network_param:
    num_chankins_corner_cutting: 200
    polyline_resampling_step: 0.5
    merging_length: 10000

# Ego vehicle parameters
###
# .. code-block:: yaml
#
#    - vehicle_number: CommonRoad vehicle number; possible options are 1, 2 or 3 (see CommonRoad vehicle models)
#    - a_max: maximum acceleration of ACC vehicle
#    - a_min: minimum acceleration of ACC vehicle
#    - j_max: maximum jerk of ACC vehicle
#    - j_min: minimum jerk of ACC vehicle
#    - v_des: desired velocity of ACC vehicle
#    - t_react: reaction time of ACC vehicle
#    - dynamics_param: physical parameters of ACC vehicle; will be initialized during runtime
#    - fov: field of view (sensor range)
#    - v_min: minimum allowed velocity considering vehicle dynamics
#    - const_dist_offset: minimum distance at standstill
#    - emergency_profile: emergency jerk profile
#    - emergency_profile_num_steps_fb: number of steps minimum jerk should be attended to emergency profile
#    - fov_speed_limit: speed limit based on field of view
#    - braking_speed_limit: speed limit to ensure comfortable braking within field of view

ego_vehicle_param:
    vehicle_number: 2
    a_max: 3
    a_min: -10.0
    a_corr: 0.0
    j_max: 10
    j_min: -10
    v_des: 30
    t_react: 0.3
    dynamics_param: None
    fov: 200
    v_min: 0
    const_dist_offset: 0
    emergency_profile: []
    emergency_profile_num_steps_fb: 200
    fov_speed_limit: None
    braking_speed_limit: None
    road_condition_speed_limit: 50

# Other vehicle's parameters
###
# .. code-block:: yaml
#
#    - vehicle_number: CommonRoad vehicle number; possible options are 1, 2 or 3 (see CommonRoad vehicle models)
#    - v_max: maximum velocity of leading vehicle
#    - v_min: minimum velocity of leading vehicle
#    - a_max: maximum acceleration of leading vehicle
#    - a_min: minimum acceleration of leading vehicle
#    - j_max: maximum jerk of leading vehicle
#    - j_min: minimum jerk of leading vehicle

other_vehicles_param:
    vehicle_number: 2
    v_max: 60
    v_min: 0
    a_max: 5
    a_min: -10.5
    j_max: 10
    j_min: -10
    dynamics_param: None  # TODO replace dynamics parameter with worst case behavior

# Visualization parameters
###
#    - Parameters for plotting of profiles
#    - Parameters for video creation
visualization:
    # Parameters for plotting of profiles
    ###
    # .. code-block:: yaml
    #
    #   - width: width of matplotlib figure
    #   - line_width: line width of profiles
    #   - font_size: font size of text within the plot
    #   - axes_line_width: line width of the axes
    #   - type of figure which should be stored
    plot:
        width: 3.75
        line_width: 0.75
        font_size: 9
        axes_line_width: 0.25
        figure_type: eps

    # Parameters for video creation
    ###
    # .. code-block:: yaml
    #
    #   - obstacle_label: activate/deactivate visualization of obstacle label (ID) in video
    video:
        obstacle_label : True

# Traffic rule information
###
#    - traffic rules formalized in temporal logic
#    - traffic rule parameters
#    - supported traffic rule sets
#    - activated traffic rule set
#    - list of traffic rules which must be evaluated with respect to several other vehicles
traffic_rule_monitoring:
    # Traffic rules formalized in metric temporal logic (MTL)
    ###
    # .. code-block:: yaml
    #
    #   - max_speed_limit: rule which evaluates maximum speed limit
    #   - min_speed_limit: rule which evaluates minimum speed limit
    #   - safe_distance: rule which evaluates safe distance
    #   - no_unnecessary_braking: rule which evaluates unnecessary strong braking
    traffic_rules:
        R_G1: G((is_in_front_of & is_in_same_lane) -> keeps_safe_distance_prec)
        R_G2: G(~(unnecessary_braking))
        R_G3: G(keeps_lane_speed_limit & keeps_fov_speed_limit & keeps_braking_speed_limit & keeps_road_condition_speed_limit & keeps_type_speed_limit)
        R_G4: G(keeps_sign_min_speed_limit)
        R_G5: G(preserves_traffic_flow)
        R_I1: G(~((in_congestion) | (exist_standing_leading_vehicle)) -> ~(in_standstill))
        R_I2: G((congestion_left & drives_with_slightly_higher_speed) | (right_of_broad_lane_marking & left_of_broad_lane_marking) | (on_access_ramp & ~(congestion_left)) | ~(drives_faster_than_vehicle_left))
        R_I3: G(~(makes_u_turn) & ~(reverses))
        R_I4: G(in_congestion -> ((interstate_broad_enough -> ((in_leftmost_lane -> drives_leftmost) & (~(in_leftmost_lane) -> drives_rightmost))) & (~(interstate_broad_enough) -> drives_rightmost)))
        R_I5: G((on_access_ramp & F(on_main_carriage_way)) -> ~(~(in_rightmost_lane) & F(in_rightmost_lane)))

    # Parameters for traffic rules
    ###
    # .. code-block:: yaml
    #
    #   - j_min_abrupt:
    #   - delta_a_abrupt:
    #   - min_velocity_dif:
    #   - standstill_error:
    #   - num_veh_congestion:
    #   - max_congestion_velocity:
    #   - max_velocity_limit_free_driving:
    #   - desired_highway_velocity:
    traffic_rules_param:
        j_abrupt: -2
        a_abrupt: -2
        min_velocity_dif: 15
        standstill_error: 0.01
        num_veh_congestion: 2
        max_congestion_velocity: 2.77
        max_velocity_limit_free_driving: 27.77
        desired_highway_velocity: 36.11
        min_interstate_width: 6.75
        close_to_lane_border: 0.1
        slightly_higher_speed_difference: 5.55
        u_turn: 1.57

    traffic_rule_sets:
        S0: [R_G1, R_G2, R_G3, R_G4, R_G5, R_I1, R_I2, R_I3, R_I4, R_I5]
        SRG1: [R_G1]
        SRG2: [R_G2]
        SRG3: [R_G3]
        SRG4: [R_G4]
        SRG5: [R_G5]
        SRI1: [R_I1]
        SRI2: [R_I2]
        SRI3: [R_I3]
        SRI4: [R_I4]
        SRI5: [R_I5]


    activated_traffic_rule_sets: [0]
    vehicle_dependent_rules: [R_G1, R_I2]
